### ISSUE TITLE
Error on utf-8

### ISSUE THREAD

**Issue by farhankn** [todatamining/textclassifiction#1]
These are the errors i Face while running
![Uploading Screenshot from 2016-04-23 12:20:37.png…]()

**Comment by farhankn** [comment]
![screenshot from 2016-04-23 12 20 37](https://cloud.githubusercontent.com/assets/6595704/14760185/41a710ca-095a-11e6-86e1-19242242ace9.png)

**Comment by todatamining** [comment]
Hi  farhankn,

Please git pull, and try again.

Good luck!
HW

**Comment by farhankn** [comment]
Worked Perfect, can you reply what has happened?
